File output support
tsaikd/golasticdump pull request #3
Opened 2020-08-13 13:19 UTC by bhrg3se

File output support like [elasticsearch-dump](https://github.com/elasticsearch-dump/elasticsearch-dump)

2020-08-15 02:01 UTC, tsaikd requested changes

2020-08-15 02:01 UTC, tsaikd commented on esdump/esdump.go
> +			return nil
```suggestion
			return setDataFile(ctx, hits, savedHits, outputFile)
```

2020-08-15 02:01 UTC, tsaikd commented on esdump/esdump.go
> +	if u.Scheme == "" {
How about using file URI scheme?
https://en.wikipedia.org/wiki/File_URI_scheme

2020-08-15 02:01 UTC, tsaikd commented on esdump/esdump.go
> +		logger.Debug("setDataFile defer with err: ", err)
```suggestion
		if err == nil {
			logger.Debug("setDataFile finish")
		} else {
			logger.Debug("setDataFile err: ", err)
		}
```

2020-08-15 02:01 UTC, tsaikd commented on esdump/esdump.go
> +	logger.Debug("setDataFile finish")
```suggestion
```

2020-08-15 02:01 UTC, tsaikd commented on esdump/esdump.go
> +	}
```suggestion
	encoder := json.NewEncoder(outputFile)
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case hit, ok := <-hits:
			if !ok {
				return nil
			}

			index := hit.Index

			logger.Debugf("setDataFile index:%q type:%q id:%q", index, hit.Type, hit.Id)

			if err = encoder.Encode(hit); err != nil {
				return err
			}
			if _, err = outputFile.WriteString("\n"); err != nil {
				return err
			}

			savedHits <- hit
		}
	}
```

2020-08-16 04:03 UTC, bhrg3se commented on esdump/esdump.go
> +	if u.Scheme == "" {
How about both file URI scheme or blank scheme for file.

Something like
`if u.Scheme == ""  || u.Scheme == "file" {`

2020-08-17 22:34 UTC, merged